### PR TITLE
Adds __heartbeat handling (new in Storm 0.9.3)

### PR DESCRIPTION
**Pull request by jasonparekh**
Without this, gostorm does not work on Storm 0.9.3.

### CODE REVIEW

**Comment by jsgilmore** [comment]
Does this change break backwards compatibility with older versions Storm?

**Comment by jsgilmore** [comment]
Nice clean implementation using conns. Thanks.

**Comment by kriztoph** [comment]
Will this be merged?

**Comment by jsgilmore** [comment]
Apologies for the delay. Merged.

**Comment by jsgilmore** [comment]
It seems the GoStorm unit tests are failing after this pull request. Please submit a pull request that fixes the unit tests or I'm going to have to roll-back this pull request.

**Comment by kriztoph** [comment]
Yeah, and I'm still getting errors with encoding `jsonEncoded` on heartbeat: 

```
9257 [Thread-19] INFO  filter_bolt - 2015/05/27 14:25:05 {"comp":null,"tuple":[],"task":-1,"stream":"__heartbeat","id":"570941336508911096"}
panic: runtime error: index out of range
```

@jasonparekh Any ideas?

**Comment by jasonparekh** [comment]
No sorry, we never ended up going the storm route so haven't maintained
this after I sent it.

**Pull request merged**
